security:
    encoders:
      App\Entity\Customer: bcrypt

    providers:
      users:
        entity:
          class: App\Entity\Customer
          property: email

    firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false

      main:
        pattern: ^/
        anonymous: true
        user_checker: App\Security\UserChecker

        form_login:
          login_path: login
          username_parameter: _email
          check_path: login_check
          csrf_token_generator: security.csrf.token_manager
          default_target_path: homepage

        remember_me:
          name: PonyvalleyRemember
          secret: '%kernel.secret%'
          lifetime: 2629800 # 1 month in seconds
          path: /

        logout:
          path: logout
          target: homepage

    role_hierarchy:
      ROLE_ADMIN:       ROLE_USER
      ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
      - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
