<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getCategories($active)
    {
        return $this->createQueryBuilder('c')
            ->where('c.id != 1')
            ->andWhere('c.status = :active')
            ->setParameter('active', $active)
            ->getQuery()
            ->getResult();
    }
}
